#!/usr/bin/with-contenv sh

if [ "$CRON" == "true" ]; then

	/usr/sbin/crond -b -L /dev/null
	#检测文件变化并执行命令
	md5_old=$(md5sum /conf/crontabs | cut -d ' ' -f1)
	while :
	do
		md5_new=$(md5sum /conf/crontabs | cut -d ' ' -f1)
		if [ "$md5_old" != "$md5_new" ]; then
			md5_old=$md5_new
			echo "`date "+%Y-%m-%d %H:%M:%S"` 检测到计划任务规则发生变化，重启crond服务"
			pid_old=$(ps -ef |grep "/usr/sbin/crond" | grep -v grep | awk '{print $1}')
			if [ $pid_old ];then
				kill -9 $pid_old
				echo "stopping..." $pid_old
			fi
			/usr/sbin/crond -b -L /dev/null
			pid_new=$(ps -ef |grep "/usr/sbin/crond" | grep -v grep | awk '{print $1}')
			echo "running..." $pid_new
		fi
		sleep 60
	done

else
    s6-svc -O .
    exit 0
fi