name: DockerBuild_caddy2

on:
  push:
    paths:
    - 'caddy2/Dockerfile'
    - 'caddy2/rootfs/**'
  workflow_dispatch:

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Set env'
        run: |
          echo "CADDY_VER=$(echo `grep -n "CADDY_VER=" caddy2/Dockerfile`|awk -F= '{print $2}')" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./caddy2
          file: ./caddy2/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            dothebetter/caddy2:latest
            dothebetter/caddy2:${{ env.CADDY_VER }}
            ghcr.io/dothebetter/caddy2:latest
            ghcr.io/dothebetter/caddy2:${{ env.CADDY_VER }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dothebetter/caddy2
          short-description: caddy2:${{ env.CADDY_VER }}，支持amd64;arm64v8;arm32v7，集成常用插件及geoipupdate
          readme-filepath: ./caddy2/README.md
          enable-url-completion: true