name: DockerBuild_kms

on:
  push:
    paths:
      - "kms/Dockerfile"
      - "kms/rootfs/**"
  workflow_dispatch:

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env and banner
        run: |
          echo "KMS_VER=$(echo `grep -n "KMS_VER=" kms/Dockerfile`|awk -F= '{print $2}')" >> $GITHUB_ENV
          sudo timedatectl set-timezone "Asia/Shanghai"
          sed -i "s@KMS_VER@$(echo `grep -n "KMS_VER=" kms/Dockerfile`|awk -F= '{print $2}')@" kms/rootfs/etc/s6-overlay/s6-rc.d/init/00-banner
          sed -i "s@DATE_TIME@$(date +"%Y/%m/%d %H:%M")@" kms/rootfs/etc/s6-overlay/s6-rc.d/init/00-banner
          cat kms/rootfs/etc/s6-overlay/s6-rc.d/init/00-banner

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./kms
          file: ./kms/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            dothebetter/kms:latest
            dothebetter/kms:${{ env.KMS_VER }}
            ghcr.io/dothebetter/kms:latest
            ghcr.io/dothebetter/kms:${{ env.KMS_VER }}
            registry.cn-hangzhou.aliyuncs.com/dothebetter/kms:latest
            registry.cn-hangzhou.aliyuncs.com/dothebetter/kms:${{ env.KMS_VER }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dothebetter/kms
          short-description: kms:${{ env.KMS_VER }}，自建KMS激活服务，带web说明，支持amd64;arm64v8;arm32v7
          readme-filepath: ./kms/README.md
          enable-url-completion: true
