name: DockerBuild_aria2

on:
  push:
    paths:
      - "aria2/Dockerfile"
      - "aria2/rootfs/**"
  workflow_dispatch:

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env and banner
        run: |
          # 同时设置 shell 变量和写入 GITHUB_ENV
          ARIA2_DOCKER_VER=$(grep -n "ARIA2_DOCKER_VER=" aria2/Dockerfile | awk -F= '{print $2}' | head -n1)
          echo "ARIA2_DOCKER_VER=$ARIA2_DOCKER_VER" >> $GITHUB_ENV

          # 提取版本号
          ARIA2_VER=$(grep -n "ARIA2_VER=" aria2/Dockerfile | awk -F= '{print $2}' | head -n1)
          AriaNg_VER=$(grep -n "AriaNg_VER=" aria2/Dockerfile | awk -F= '{print $2}' | head -n1)
          FileBrowser_VER=$(grep -n "FileBrowser_VER=" aria2/Dockerfile | awk -F= '{print $2}' | head -n1)

          # 设置时区
          sudo timedatectl set-timezone "Asia/Shanghai"

          # 替换 banner 文件中的占位符
          sed -i "s@ARIA2_DOCKER_VER@$ARIA2_DOCKER_VER@" aria2/rootfs/etc/s6-overlay/s6-rc.d/init/00-banner
          sed -i "s@DATE_TIME@$(date +"%Y/%m/%d %H:%M")@" aria2/rootfs/etc/s6-overlay/s6-rc.d/init/00-banner
          
          sed -i "s@ARIA2_VER@$ARIA2_VER@" aria2/rootfs/etc/s6-overlay/s6-rc.d/init/00-banner.sh
          sed -i "s@AriaNg_VER@$AriaNg_VER@" aria2/rootfs/etc/s6-overlay/s6-rc.d/init/00-banner.sh
          sed -i "s@FileBrowser_VER@$FileBrowser_VER@" aria2/rootfs/etc/s6-overlay/s6-rc.d/init/00-banner.sh

          # 打印文件内容查看结果
          cat aria2/rootfs/etc/s6-overlay/s6-rc.d/init/00-banner
          
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./aria2
          file: ./aria2/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            dothebetter/aria2:latest
            dothebetter/aria2:${{ env.ARIA2_DOCKER_VER }}
            ghcr.io/dothebetter/aria2:latest
            ghcr.io/dothebetter/aria2:${{ env.ARIA2_DOCKER_VER }}
            registry.cn-hangzhou.aliyuncs.com/dothebetter/aria2:latest
            registry.cn-hangzhou.aliyuncs.com/dothebetter/aria2:${{ env.ARIA2_DOCKER_VER }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dothebetter/aria2
          short-description: aria2:${{ env.ARIA2_DOCKER_VER }}，自用Aria2+AriaNg+FileBrowser下载镜像，支持amd64;arm64v8;arm32v7
          readme-filepath: ./aria2/README.md
          enable-url-completion: true
