name: DockerBuild_zerotier-client

on:
  push:
    paths:
    - 'zerotier-client/Dockerfile'
    - 'zerotier-client/rootfs/**'
  workflow_dispatch:

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Set env'
        run: |
          echo "ZeroTierOne_VER=$(echo `grep -n "ZeroTierOne_VER=" zerotier-client/Dockerfile`|awk -F= '{print $2}')" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5-43
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./zerotier-client
          file: ./zerotier-client/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            dothebetter/zerotier-client:latest
            dothebetter/zerotier-client:${{ env.ZeroTierOne_VER }}
            ghcr.io/dothebetter/zerotier-client:latest
            ghcr.io/dothebetter/zerotier-client:${{ env.ZeroTierOne_VER }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dothebetter/zerotier-client
          short-description: zerotier-client:${{ env.ZeroTierOne_VER }} alpine镜像，支持amd64;arm64v8;arm32v7，以网关模式访问内网
          readme-filepath: ./zerotier-client/README.md
          enable-url-completion: true